const $=s=>document.querySelector(s); let current=null;
const demos={
pool:`2026-08-20 09:11:58 [WARN] [SQL] slow query duration=6830ms SELECT * FROM Orders WHERE CustomerId=4711
2026-08-20 09:12:03 [ERROR] [SQL] execution timeout expired after 30s database request
2026-08-20 09:12:04 [WARN] [App] retry database request attempt=1
2026-08-20 09:12:07 [CRITICAL] [DB] Connection pool exhausted; max pool size reached
2026-08-20 09:12:08 [ERROR] [Web] HTTP 500 /api/orders
2026-08-20 09:12:09 [ERROR] [SQL] execution timeout expired after 30s database request
2026-08-20 09:12:12 [CRITICAL] [DB] Connection pool exhausted; max pool size reached
2026-08-20 09:12:15 [ERROR] [Web] status 503 service unavailable`,
deadlock:`2026-08-20 10:14:01 [INFO] [OrderService] begin update order 481
2026-08-20 10:14:03 [WARN] [SQL] slow query duration=7211ms UPDATE Orders SET Status='Booked'
2026-08-20 10:14:05 [ERROR] [SQL] Transaction (Process ID 82) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Error 1205
2026-08-20 10:14:06 [WARN] [OrderService] retry after deadlock attempt=1
2026-08-20 10:14:12 [ERROR] [SQL] execution timeout expired database request`,
mixed:`2026-08-20 11:00:01 [ERROR] [Auth] Login failed for user 'report_user'. Error 18456
2026-08-20 11:00:02 [ERROR] [Auth] Login failed for user 'report_user'. Error 18456
2026-08-20 11:05:12 [WARN] [Import] File not found C:\Import\orders.csv
2026-08-20 11:08:21 [ERROR] [API] System.NullReferenceException: Object reference not set to an instance of an object
2026-08-20 11:08:21 [ERROR] [Web] HTTP 500 /api/customer/42
2026-08-20 11:12:30 [CRITICAL] [SQL] The transaction log for database 'ERP' is full. Error 9002
2026-08-20 11:15:00 [WARN] [Net] transport-level error: connection reset by peer`};
$('#choose').onclick=()=>$('#file').click(); $('#file').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);
$('#drop').ondragover=e=>{e.preventDefault();$('#drop').classList.add('drag')}; $('#drop').ondragleave=()=>$('#drop').classList.remove('drag'); $('#drop').ondrop=e=>{e.preventDefault();$('#drop').classList.remove('drag'); const f=e.dataTransfer.files[0];if(f)loadFile(f)};
document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>analyzeClient('Demo_'+b.dataset.demo+'.log',demos[b.dataset.demo]));
async function loadFile(f){const text=await f.text(); if(await tryBackend(f))return; analyzeClient(f.name,text)}
async function tryBackend(f){try{const fd=new FormData();fd.append('file',f);const r=await fetch('/api/analyze',{method:'POST',body:fd});if(!r.ok)return false;current=await r.json();render(current);status('Analyse über ASP.NET-Core-Backend abgeschlossen.');return true}catch{return false}}
function analyzeClient(name,text){const rows=text.split(/\r?\n/).filter(Boolean);const events=rows.map((raw,i)=>parseLine(raw,i+1));const tagged=events.map(e=>({...e,category:category(e),severity:severity(e)}));const by={};tagged.filter(x=>x.category!='Other').forEach(x=>(by[x.category]??=[]).push(x));const clusters=Object.entries(by).map(([k,v])=>({category:k,severity:v.sort((a,b)=>score(b.severity)-score(a.severity))[0].severity,count:v.length,example:v[0].message,first:v[0].timestamp,last:v[v.length-1].timestamp})).sort((a,b)=>score(b.severity)-score(a.severity)||b.count-a.count);const findings=clusters.map(c=>finding(c,by[c.category]));const chains=detectChains(tagged);const errors=events.filter(e=>['ERROR','FATAL','CRITICAL'].includes(e.level)).length,warnings=events.filter(e=>e.level==='WARN').length;current={fileName:name,totalLines:rows.length,parsedEvents:events.length,errors,warnings,clusters,findings,chains,aiSummary:summary(name,events.length,errors,warnings,clusters,findings,chains),events};render(current);status('Offline-Analyse direkt im Browser abgeschlossen. SQL-Speicherung benötigt das ASP.NET-Core-Backend.')}
function parseLine(raw,line){const m=raw.match(/^(\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:[.,]\d+)?)?\s*(?:\[(TRACE|DEBUG|INFO|WARN|WARNING|ERROR|FATAL|CRITICAL)\]|(TRACE|DEBUG|INFO|WARN|WARNING|ERROR|FATAL|CRITICAL))?\s*(?:\[([^\]]+)\])?\s*(.*)$/i)||[];let level=(m[2]||m[3]||inferLevel(raw)).toUpperCase();if(level==='WARNING')level='WARN';return{timestamp:m[1]||'',level,source:m[4]||inferSource(raw),message:m[5]||raw,line,raw}}
function inferLevel(s){return /FATAL/i.test(s)?'FATAL':/ERROR/i.test(s)?'ERROR':/WARN/i.test(s)?'WARN':'INFO'}function inferSource(s){return /sql|database/i.test(s)?'SQL':/http|api/i.test(s)?'Web':'Application'}
function category(e){const s=(e.message+' '+e.raw).toLowerCase();if(/deadlock|1205/.test(s))return'Deadlock';if(/connection pool|pool exhausted|max pool size/.test(s))return'Connection Pool';if(/(timeout|timed out)/.test(s)&&/(sql|database|db|execution)/.test(s))return'SQL Timeout';if(/login failed|authentication failed|18456/.test(s))return'Login Failure';if(/disk full|no space left|insufficient disk|9002|transaction log.*full/.test(s))return'Disk Space';if(/file not found|could not find file|directorynotfound/.test(s))return'File Missing';if(/nullreference|object reference not set|null pointer/.test(s))return'Null Reference';if(/http 500|status 500| 502 | 503 /.test(s))return'HTTP 5xx';if(/network|connection reset|connection refused|host unreachable|transport-level error/.test(s))return'Network';if(/slow query/.test(s)||/duration=(?:[5-9]\d{3}|\d{5,})/.test(s))return'Slow Query';return'Other'}
function severity(e){const c=category(e);if(['Disk Space','Connection Pool'].includes(c))return'CRITICAL';if(['Deadlock','SQL Timeout','HTTP 5xx','Login Failure','Null Reference'].includes(c))return'ERROR';if(['Network','Slow Query','File Missing'].includes(c))return'WARN';return e.level}function score(s){return({CRITICAL:4,FATAL:4,ERROR:3,WARN:2,INFO:1}[s]||1)}
function finding(c,rows){const map={'SQL Timeout':['Datenbank-Timeouts erkannt','Langsame Abfragen, Sperren, Indizes und Connection-Pooling prüfen.'],'Connection Pool':['Connection Pool erschöpft','Offene Verbindungen, Dispose/using und Pool-Konfiguration kontrollieren.'],'Login Failure':['Fehlgeschlagene Anmeldungen','Benutzer, Kennwort, Berechtigungen und Fehlkonfiguration prüfen.'],'Deadlock':['SQL-Deadlocks erkannt','Deadlock-Graph analysieren, Transaktionsreihenfolge und Indizes optimieren.'],'Disk Space':['Speicherplatzproblem','Freien Speicher, Logwachstum und Bereinigungs-/Archivierungsjobs prüfen.'],'HTTP 5xx':['Serverfehler im Web/API-Betrieb','Requests mit den unmittelbar davorliegenden Fehlern korrelieren.'],'File Missing':['Datei oder Pfad nicht gefunden','Pfad, Berechtigungen, Deployment und Netzlaufwerke kontrollieren.'],'Null Reference':['Null-/Objektreferenzfehler','Stacktrace und Eingabedaten prüfen; Null-Checks ergänzen.'],'Network':['Netzwerk-/Verbindungsabbrüche','DNS, Firewall, Erreichbarkeit und Retry-Strategie überprüfen.'],'Slow Query':['Langsame Datenbankabfragen','Query-Plan, Indizes, Statistiken und Parameter-Sniffing untersuchen.']};const [title,recommendation]=map[c.category]||[c.category+' erkannt','Zeitlichen Kontext prüfen.'];return{severity:c.severity,category:c.category,title,detail:c.count+' Vorkommen; Beispiel: '+c.example,count:c.count,recommendation,lines:rows.slice(0,50).map(x=>x.line)}}
function detectChains(t){const out=[];for(let i=0;i<t.length;i++){if(t[i].category==='SQL Timeout'){const near=t.slice(Math.max(0,i-2),i+6);if(near.some(x=>x.category==='Connection Pool'||x.category==='HTTP 5xx')){out.push({name:'Datenbank-Fehlerkette',severity:'CRITICAL',explanation:'SQL-Timeout, Connection-Pool und Serverfehler treten im selben Zeitfenster auf.',steps:near.filter(x=>['Slow Query','SQL Timeout','Connection Pool','HTTP 5xx'].includes(x.category)).map(x=>({timestamp:x.timestamp,label:x.category,message:x.message,line:x.line}))});break}}}const d=t.findIndex(x=>x.category==='Deadlock');if(d>=0)out.push({name:'Deadlock / Retry',severity:'ERROR',explanation:'Deadlock und nachfolgende Datenbankfehler sollten gemeinsam untersucht werden.',steps:t.slice(Math.max(0,d-2),d+5).filter(x=>['Deadlock','SQL Timeout','Slow Query'].includes(x.category)).map(x=>({timestamp:x.timestamp,label:x.category,message:x.message,line:x.line}))});return out}
function summary(name,total,errors,warnings,clusters,findings,chains){if(!clusters.length)return`${name}: ${total} Ereignisse analysiert. Keine bekannten kritischen Fehlermuster erkannt.`;return`${name}: ${total} Ereignisse analysiert, davon ${errors} Fehler und ${warnings} Warnungen. Schwerpunkte: ${clusters.slice(0,3).map(c=>`${c.category} (${c.count})`).join(', ')}. ${findings.filter(f=>['CRITICAL','ERROR'].includes(f.severity)).length} Befunde sollten priorisiert geprüft werden.${chains.length?' Zusätzlich wurde '+chains.length+' Fehlerkette erkannt.':''}`}
function render(r){$('#result').classList.remove('hidden');$('#mTotal').textContent=r.totalLines;$('#mErrors').textContent=r.errors;$('#mWarn').textContent=r.warnings;$('#mFind').textContent=r.findings.length;$('#summary').textContent=r.aiSummary;$('#clusters').innerHTML=r.clusters.length?r.clusters.map(c=>`<div class="cluster"><div><b>${esc(c.category)}</b><small>${esc(c.example)}</small></div><div><span class="sev ${c.severity}">${c.severity}</span><br><b>${c.count}×</b></div></div>`).join(''):'<p>Keine Cluster.</p>';$('#findings').innerHTML=r.findings.map(f=>`<tr><td><span class="sev ${f.severity}">${f.severity}</span></td><td>${esc(f.category)}</td><td><b>${esc(f.title)}</b><br><small>${esc(f.detail)}</small></td><td>${f.count}</td><td>${esc(f.recommendation)}</td></tr>`).join('');$('#chains').innerHTML=r.chains.map(c=>`<div class="chain"><b>⚠ ${esc(c.name)}</b><p>${esc(c.explanation)}</p><ol>${c.steps.map(s=>`<li><b>${esc(s.label)}</b> · ${esc(s.timestamp||'')} · ${esc(s.message)}</li>`).join('')}</ol></div>`).join('');renderEvents(r.events)}
function renderEvents(events){const q=$('#filter').value.toLowerCase();$('#events').innerHTML=events.filter(e=>!q||(e.level+' '+e.source+' '+e.message).toLowerCase().includes(q)).slice(0,1500).map(e=>`<tr><td>${esc(e.timestamp||'')}</td><td><span class="sev ${e.level}">${e.level}</span></td><td>${esc(e.source)}</td><td>${esc(e.message)}</td></tr>`).join('')}$('#filter').oninput=()=>current&&renderEvents(current.events);
function status(t,err=false){$('#status').textContent=t;$('#status').classList.toggle('error',err)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#csvBtn').onclick=()=>{if(!current)return;const rows=[['Prioritaet','Kategorie','Befund','Anzahl','Empfehlung'],...current.findings.map(f=>[f.severity,f.category,f.title,f.count,f.recommendation])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='Loganalyse_Bericht.csv';a.click()};
$('#persistBtn').onclick=async()=>{if(!current)return;try{const r=await fetch('/api/analysis/persist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(current)});const x=await r.json();if(!r.ok)throw Error(x.error||'Fehler');status('Analyse in SQL Server gespeichert. Run-ID: '+x.analysisRunId)}catch(e){status('SQL-Speicherung nicht verfügbar: '+e.message,true)}};
$('#settingsBtn').onclick=async()=>{$('#settings').classList.remove('hidden');try{const r=await fetch('/api/settings/db');if(r.ok){const x=await r.json();$('#dbServer').value=x.server;$('#dbName').value=x.database;$('#dbTrusted').checked=x.trustedConnection;$('#dbUser').value=x.userId||''}}catch{}};$('#closeSettings').onclick=()=>$('#settings').classList.add('hidden');
function dbObj(){return{server:$('#dbServer').value,database:$('#dbName').value,trustedConnection:$('#dbTrusted').checked,userId:$('#dbUser').value||null,trustServerCertificate:true}}
$('#saveDb').onclick=async()=>{try{const r=await fetch('/api/settings/db',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(dbObj())});if(!r.ok)throw Error('Backend nicht erreichbar');$('#dbStatus').textContent='Gespeichert. Connection String wurde ohne Codeänderung aktualisiert.'}catch(e){$('#dbStatus').textContent='Nur mit ASP.NET-Core-Backend speicherbar: '+e.message}}
$('#testDb').onclick=async()=>{try{$('#dbStatus').textContent='Teste…';const r=await fetch('/api/settings/db/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dbObj())});const x=await r.json();if(!r.ok)throw Error(x.error||'Verbindung fehlgeschlagen');$('#dbStatus').textContent=`OK: ${x.server} / ${x.database} · SQL ${x.version}`}catch(e){$('#dbStatus').textContent='Fehler: '+e.message}}
